### PR TITLE
Vendor List Operational

### PR DESCRIPTION
**Pull request by Zafuzi**
## What's Happening?
added custom styling for vendors
fixed home page links to vendor-list.html
added section to include scripts in layout.html
added function to display vendors returned from AJAX call in main.js

#### Possible Breaking Changes
* No breaking changes

## Testing and Deployment Checklist

- [ ] Click on a vendor on the main page, it should take you to a list of those vendors

currently there is only two vendor types with data in the DB. Venues and Photographers. If you want to see the others I recommend creating new vendors.

### CODE REVIEW

**Comment by Zafuzi** [comment]
Just a side note, the design doesn't matter at all, it was really just for me to test. But honestly the pink background on everything has got to go. Super garish.

**Review by KLSharkey — APPROVED** [review]
Looks good to me. I'd definitely wait until a front end person checks it out though just in case.

**Review by CatherineEvelyn — APPROVED** [review]
agree on pink background comment, can't we keep the greyish background from the original?

**Review by seanmstevens — COMMENTED** [review]
Looks good, although I have a bunch of changes that I still need to push to this branch as well, so maybe we can hold off on merging it right away. Pink background was just a placeholder until we developed a colorscheme, so maybe the front end folks can all take a little time and come up with a base color, accents, and additional colors that we can all agree on?

**Comment by CatherineEvelyn** [comment]
Yeah, by Monday we will have something (color scheme) for everyone to review

**Comment by seanmstevens** [comment]
I added a bunch of changes, so if folks want to do another review to make sure everything works, go ahead. Otherwise, we can merge to master.

**Pull request merged**
