### PR TITLE
create sitemap

### PR DESCRIPTION
**Pull request by CatherineEvelyn**
## What's Happening?
Created pages with TO DO list in them, explaining what the page is for and how to navigate to and from that page, essentially creating a sitemap.

#### New in this Release
* organize all html files (renamed, deleted, created, added to do list)

#### Bug
* several links and route on main.py will need to be edited to match the name of html page it refers to

#### Cleanup & Other
* Cleaned up all html files inside template folder

#### Possible Breaking Changes
* This will break some app route and links on main.py because a couple pages were renamed, can someone please fix this before merging this branch to master? Thank you.

## Related
It's important to get this merge to master branch ASAP so we can move forward using correct pages when navigating links and route on our code.

### CODE REVIEW

**Review by KLSharkey — APPROVED** [review]
This looks good to me.

**Review by xiuda — APPROVED** [review]
Thanks for the cleanup!

**Review by seanmstevens — APPROVED** [review]
Looks good to me!

**Review by Zafuzi — APPROVED** [review]
Looks good

**Pull request merged**
