### PR TITLE
Enable disable

### PR DESCRIPTION
**Pull request by KLSharkey**
## What's Happening?
I updated the DB so that the association table user-vendor has a column called "enable" that can be set to 1 (True/yes) or 0 (False/no) so that we can use the cancel button on the organizer page to cancel a booking (in other words, turn it to 0). I updated the join table in the organizer path so that it will only show the associations that are not disabled. When a booking is made, enabled is set to 1. I also defaulted it to True just in case. 

### Bug Fix 1
1.No bug fixes, just added feature

#### New in this Release
* updated only main.py

#### Possible Breaking Changes
* Should be no breaking changes, just make sure you pull it before booking as it will now need the enabled initialization since the DB has been changed. 
*Will will need to change the vendor's booked page though as it will need to have the condition of enabled = 1. 

## Related
* Closes issue #68

## Testing and Deployment Checklist

- [ ] Check to make sure when you book a vendor, the vendor shows up on your organizer page.

### CODE REVIEW

**Review by seanmstevens — APPROVED** [review]
Your changes look good to me. It looks like the vendorPageExtended branch's changes were also included, though. I don't really have any problem with merging them all at once, since I was going to merge my changes separately anyway.

**Comment by KLSharkey** [comment]
Sean, I'm not even quite sure how I got your changes (could have been when I did the pull request last night in class?) But I guess it worked out since I had the correct file path for the dist folder!

**Comment by seanmstevens** [comment]
Yeah, I'd guess that it happened when you pulled from my branch last night to fix the dist issue.

**Comment by CatherineEvelyn** [comment]
That commit is just the git ignore files from the class yesterday. Looks good to me, merge it.

**Review by CatherineEvelyn — APPROVED** [review]

**Pull request merged**
