### PR TITLE
Association table

### PR DESCRIPTION
**Pull request by KLSharkey**
What's Happening?

I have the code in (some hard coded - need a session for it not to be) for connecting to the user and vendor profile pages (vendor-account.html and user-account.html). I have two test files testUserVendor,html for testing user's profile and testVendorsProfile to test the vendor's profile.
I also changed the data type of phoneNumber to BIGINT and eventDate in the association table is now called "bookedDate" as to not get confused with the eventDate listed in the user table. 

Possible Breaking Changes

*Note how I set up the vendor and user lists in the html file. This is because of how I have to get the data from the DB with my queries.

Related

Closes issue #47
Closes issue #39

Testing and Deployment Checklist

 Check to make sure accuracy of loaded vendors and users.

MUST HAVE ALL INFO FILLED IN FOR EACH COLUMN FOR THIS TO WORK CORRECTLY (ie. users name, email, phone number, etc)

### CODE REVIEW

**Review by seanmstevens — APPROVED** [review]
Looks good. Could we add a 'user type' that is initialized at login, which is stored in the session object, and basically tells the backend whether a user or vendor is accessing different pages? It might make passing information to the templates a bit easier; rather than having a ton of conditional blocks in the template, we can just have one in the profile route that will check whether a vendor or user exists with the login credentials provided.

**Review by Zafuzi — COMMENTED** [review]
To load the correct user logged in you need to change line 176 to say:
users_info=User.query.filter_by(email=session["email"]).first()

Everything else seems to be working fine.

**Review by Zafuzi — CHANGES_REQUESTED** [review]
To load the correct user logged in you need to change line 176 to say:
users_info=User.query.filter_by(email=session["email"]).first()

Everything else seems to be working fine.

**Comment by KLSharkey** [comment]
Yeah, it's hard coded for testing purposes.

**Review by Zafuzi — APPROVED** [review]

**Pull request merged**
