### PR TITLE
Sitemap

### PR DESCRIPTION
**Pull request by CatherineEvelyn**
## What's Happening?
Created pages with TO DO list in them, explaining what the page is for and how to navigate to and from that page, essentially creating a sitemap.

#### New in this Release
* organize all html files (renamed, deleted, created, added to do list)

#### Bug
* several links and route on main.py will need to be edited to match the name of html page it refers to

#### Cleanup & Other
* Cleaned up all html files inside template folder

#### Possible Breaking Changes
* This will break some app route and links on main.py because a couple pages were renamed, can someone please fix this before merging this branch to master? Thank you.

## Related
It's important to get this merge to master branch ASAP so we can move forward using correct pages when navigating links and route on our code.

### CODE REVIEW

**Review by xiuda — CHANGES_REQUESTED** [review]
It looks like you pulled in the changes from bulma's branch here (maybe you did a `git rebase` or something else.  But it's best practice to have only the changes you are making included.

Please do a `git rebase -i` and write "drop" next to all of the commits that are not yours.  Push again and this PR should have only the sitemap changes.

**Review by seanmstevens — COMMENTED** [review]
Like Suzanne said, the Bulma commits should be removed before merging so that we can separate our issues.
Here's a list of the commits you need to drop using Suzanne's method above:
91021ba1971e00ac052afd03ebfc46e4cb18bbc1
955d0db27c64e26eb6f2bab14e59895aebed0e0d
fb25e535cc06e2136e10dd7ef9ef01b6daf4727f
7825ddbbf54e7edbbbd32c1d657371c307881300
2459121a7892b83defacd171ae42d0938692c8cc
9b994dcad1ae4486ac088b700dcf93a079496037
a48d24223d262bb7e3a70753838eac55013fe0e9

**Comment by CatherineEvelyn** [comment]
I didn't notice that mistake, you're right, there was bulma changes got mixed up, I'll try fixing it

**Comment by CatherineEvelyn** [comment]
I wasn't 100% sure how to rebase so I just made another branch and remake the skeleton pages. Can we delete this pull request? I'm just going to merge the sitemap2 branch to master.

**Pull request closed without merging**
